"""add price_bars

Revision ID: 423650f7fa82
Revises: 7b2f6d9a1c4e
Create Date: 2026-02-09 00:35:10.950349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423650f7fa82'
down_revision: Union[str, Sequence[str], None] = '7b2f6d9a1c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bars',
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bar_id'),
    sa.UniqueConstraint('symbol', 'day', 'source', name='uq_price_bar_symbol_day_source')
    )
    op.create_index('ix_price_bar_symbol_day', 'price_bars', ['symbol', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_bar_symbol_day', table_name='price_bars')
    op.drop_table('price_bars')
    # ### end Alembic commands ###
