"""watchlist constraints

Revision ID: cd42a415ef5a
Revises: 2f3c1a9b6c7d
Create Date: 2026-01-24 20:27:18.314142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd42a415ef5a'
down_revision: Union[str, Sequence[str], None] = '2f3c1a9b6c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_watchlist_stock_id', 'watchlist', ['stock_id'], unique=False)
    op.create_index('ix_watchlist_user_id', 'watchlist', ['user_id'], unique=False)
    op.create_unique_constraint('uq_watchlist_user_stock', 'watchlist', ['user_id', 'stock_id'])
    op.create_foreign_key(None, 'watchlist', 'stocks', ['stock_id'], ['stock_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watchlist', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_constraint('uq_watchlist_user_stock', 'watchlist', type_='unique')
    op.drop_index('ix_watchlist_user_id', table_name='watchlist')
    op.drop_index('ix_watchlist_stock_id', table_name='watchlist')
    # ### end Alembic commands ###
